import type { Recipe } from './types'

export const sampleRecipe: Recipe = {
  id: 'recipe-paracetamol-solucao',
  code: 'SOL-PAR-500',
  name: 'Solução oral de paracetamol 500 mg',
  product: 'Paracetamol solução oral 500 mg/15 mL',
  version: '1.0',
  steps: [
    {
      id: 'pesagem',
      order: 1,
      name: 'Pesagem de insumos',
      description: 'Pesar as matérias-primas conforme a ordem de manipulação.',
      parameters: [
        { id: 'paracetamol', label: 'Paracetamol', value: '500', unit: 'mg' },
        { id: 'veiculo', label: 'Veículo', value: '15', unit: 'mL' },
      ],
      requiredFields: [
        { id: 'lote-insumo', label: 'Lote do insumo', kind: 'text', required: true },
        {
          id: 'massa-pesada',
          label: 'Massa pesada',
          kind: 'number',
          required: true,
          unit: 'mg',
          min: 500,
          max: 510,
          helperText: 'Tolerância de 2% sobre a massa teórica.',
        },
        {
          id: 'balanca-calibrada',
          label: 'Balança calibrada no turno',
          kind: 'boolean',
          required: true,
        },
      ],
    },
    {
      id: 'preparo',
      order: 2,
      name: 'Preparo da solução',
      description: 'Dissolver o ativo no veículo e ajustar os parâmetros do processo.',
      parameters: [
        { id: 'temperatura', label: 'Temperatura', value: '25', unit: '°C' },
        { id: 'ph', label: 'pH final', value: '5,5' },
      ],
      requiredFields: [
        {
          id: 'volume-agua',
          label: 'Volume de água purificada',
          kind: 'number',
          required: true,
          unit: 'mL',
          min: 15,
          max: 15.5,
        },
        {
          id: 'temperatura-medida',
          label: 'Temperatura medida',
          kind: 'number',
          required: true,
          unit: '°C',
          min: 20,
          max: 30,
        },
        {
          id: 'ph-medido',
          label: 'pH medido',
          kind: 'number',
          required: true,
          min: 5,
          max: 6,
        },
        {
          id: 'aspecto-conforme',
          label: 'Solução límpida e sem partículas',
          kind: 'boolean',
          required: true,
        },
      ],
    },
    {
      id: 'envase',
      order: 3,
      name: 'Envase',
      description: 'Envasar a solução nos frascos respeitando o volume alvo.',
      parameters: [{ id: 'volume-frasco', label: 'Volume por frasco', value: '15', unit: 'mL' }],
      requiredFields: [
        { id: 'lote-envase', label: 'Lote de envase', kind: 'text', required: true },
        {
          id: 'equipamento',
          label: 'Envasadora utilizada',
          kind: 'select',
          required: true,
          options: ['Envasadora A', 'Envasadora B'],
        },
        {
          id: 'volume-envasado',
          label: 'Volume envasado',
          kind: 'number',
          required: true,
          unit: 'mL',
          min: 15,
          max: 15.2,
        },
        {
          id: 'frascos-aprovados',
          label: 'Frascos aprovados',
          kind: 'number',
          required: true,
          min: 1,
        },
      ],
    },
    {
      id: 'rotulagem',
      order: 4,
      name: 'Rotulagem',
      description: 'Aplicar e conferir os rótulos do lote.',
      parameters: [{ id: 'rotulo', label: 'Rótulo aprovado', value: 'ROT-PAR-500' }],
      requiredFields: [
        { id: 'lote-rotulo', label: 'Lote do rótulo', kind: 'text', required: true },
        {
          id: 'conferencia-dados',
          label: 'Dados do rótulo conferidos',
          kind: 'boolean',
          required: true,
        },
      ],
    },
    {
      id: 'liberacao',
      order: 5,
      name: 'Liberação do lote',
      description: 'Registrar a avaliação final do lote pela qualidade.',
      parameters: [{ id: 'criterio', label: 'Critério', value: 'Laudo aprovado' }],
      requiredFields: [
        { id: 'laudo-aprovado', label: 'Laudo aprovado', kind: 'boolean', required: true },
        { id: 'responsavel', label: 'Responsável pela liberação', kind: 'text', required: true },
        {
          id: 'observacoes',
          label: 'Observações',
          kind: 'text',
          required: false,
          multiline: true,
        },
      ],
    },
  ],
}
